apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: tech-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php-fpm
          image: tech-challenge-php:latest
          # Never = usa imagem local do Minikube, nao tenta baixar da internet
          # Na AWS, trocar para "Always" e apontar para o ECR
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          # envFrom injeta todas as variaveis do ConfigMap e Secret de uma vez
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          # PHP-FPM nao tem endpoint HTTP, entao verificamos se a porta TCP esta aberta
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
          # requests e obrigatorio para o HPA calcular o percentual de uso
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"