sonar.issue.ignore.multicriteria=snakeCaseContracts

sonar.issue.ignore.multicriteria.snakeCaseContracts.ruleKey=php:S117,php:S116
sonar.issue.ignore.multicriteria.snakeCaseContracts.resourceKey=src/*/Contracts/**/*.php
