sonar.projectKey=oesleik_tech-chalange
sonar.organization=oesleik

sonar.sources=src
sonar.exclusions=vendor/**,public/**,docs/**,**/*Test.php,src/cmd/*,src/Middleware/OpenTelemetryMiddleware.php
sonar.cpd.exclusions=**/*Test.php

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.php.unitTest.reportPaths=coverage/junit.xml
