sonar.projectKey=
sonar.organization=
sonar.sources=src
sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.php.unitTest.reportPaths=coverage/junit.xml
sonar.exclusions=vendor/**,public/**,docs/**
