apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: tech-challenge
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      # NodePort expoe uma porta no host, intervalo valido: 30000 a 32767
      nodePort: 30080
  # LOCAL: NodePort | AWS: LoadBalancer (remove o nodePort acima)
  type: NodePort