apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  accessModes:
    # ReadWriteOnce = so um node escreve por vez, correto para banco de dados
    - ReadWriteOnce
  {{- if .Values.mysql.persistence.storageClassName }}
  storageClassName: {{ .Values.mysql.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
