apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    {{- include "tech-challenge.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Files.Get "files/nginx-default.conf" | indent 4 }}
