apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  selector:
    app: php
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
{{- if .Values.php.hpa.enabled }}
