apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.php.replicaCount }}
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php-fpm
          image: {{ .Values.php.image }}
          imagePullPolicy: {{ .Values.php.imagePullPolicy }}
          ports:
            - containerPort: 9000
          # envFrom injeta todas as variaveis do ConfigMap e Secret de uma vez
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          # PHP-FPM nao tem endpoint HTTP, entao verificamos se a porta TCP esta aberta
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
