{{- if .Values.phpmyadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image }}
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: {{ .Values.config.DB_HOST | quote }}
            - name: PMA_PORT
              value: {{ .Values.config.DB_PORT | quote }}
            - name: PMA_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USERNAME
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
          resources:
            {{- toYaml .Values.phpmyadmin.resources | nindent 12 }}
