apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    {{- include "tech-challenge.labels" . | nindent 4 }}
# Opaque = tipo generico para dados arbitrarios
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
