apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tech-challenge
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  # ClusterIP = so acessivel dentro do cluster, banco nunca exposto externamente
  type: ClusterIP