apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: tech-challenge
data:
  # o "|" indica texto multiline, o conteudo e o proprio arquivo default.conf
  default.conf: |
    server {
        listen 80;
        root /var/www/html/public;
        index index.php;

        gzip on;
        gzip_types text/plain text/css application/json application/javascript;

        add_header X-Content-Type-Options "nosniff" always;
        add_header Cross-Origin-Resource-Policy "same-origin" always;
        add_header X-Frame-Options "SAMEORIGIN" always;

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
            # "php" e o nome do Service do PHP, o K8s resolve o DNS
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_read_timeout 300;
        }

        location ~ /\. {
            deny all;
        }

        # no K8s, logs vao para stdout/stderr e sao capturados pelo cluster
        error_log  /dev/stderr;
        access_log /dev/stdout;
    }