apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "mysql"
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USERNAME
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: tech-challenge
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort